### PR TITLE
packit: initial config

### PR DESCRIPTION
**Pull request by mrc0mmand**
- [x] enable Packit on Fedora Rawhide
 - [ ] attempt to run a few *simple* tests (use FMF & a separate repository) with enabled SELinux

### CODE REVIEW

**Comment by mrc0mmand** [comment]
Fix for the rpmbuild/patch issue: https://github.com/packit-service/packit/pull/765

**Comment by TomasTomecek** [comment]
I just tried this pr with the packit patch ^ and it's still not correct:
```
+ /usr/bin/cat /builddir/build/SOURCES/40-0002-docs-fix-typo.patch
+ /usr/bin/git apply --index -p1 -
+ /usr/bin/git commit -q -m 40-0002-docs-fix-typo.patch --author 'rpm-build <rpm-build>'
+ /usr/bin/cat /builddir/build/SOURCES/41-0001-linux-add-can-netlink.h.patch
+ /usr/bin/git apply --index -p1 -
<stdin>:48: tab in indent.
        __u32 bitrate;          /* Bit-rate in bits/second */
<stdin>:49: tab in indent.
        __u32 sample_point;     /* Sample point in one-tenth of a percent */
<stdin>:50: tab in indent.
        __u32 tq;               /* Time quanta (TQ) in nanoseconds */
<stdin>:51: tab in indent.
        __u32 prop_seg;         /* Propagation segment in TQs */
<stdin>:52: tab in indent.
        __u32 phase_seg1;       /* Phase buffer segment 1 in TQs */
warning: squelched 47 whitespace errors
warning: 52 lines add whitespace errors.
+ /usr/bin/git commit -q -m 41-0001-linux-add-can-netlink.h.patch --author 'rpm-build <rpm-build>'
+ /usr/bin/cat /builddir/build/SOURCES/42-0002-network-add-CAN-Termination-tristate-option.patch
+ /usr/bin/git apply --index -p1 -
error: patch failed: src/network/networkd-network-gperf.gperf:251
error: src/network/networkd-network-gperf.gperf: patch does not apply                                                    ```

**Comment by mrc0mmand** [comment]
@TomasTomecek thanks for the testing & patch, this is indeed weird. Will the patch get to the staging instance anytime soon so I can debug it further?

**Comment by mrc0mmand** [comment]
@TomasTomecek 
> Edit: no idea what's wrong but git generated the patch incorrectly:
> 
> git commit:
> 
> ```
> + * at http://www.semiconductors.bosch.de/pdf/can2spec.pdf.
> + */
> +struct can_bittiming {
> +       __u32 bitrate;          /* Bit-rate in bits/second */
> +       __u32 sample_point;     /* Sample point in one-tenth of a percent */
> ```
> 
> patch:
> 
> ```
> + * at http://www.semiconductors.bosch.de/pdf/can2spec.pdf.
> + */
> +struct can_bittiming {
> +	__u32 bitrate;		/* Bit-rate in bits/second */
> +	__u32 sample_point;	/* Sample point in one-tenth of a percent */
> ```
> 
> (notice the tabs)

Actually, the tabs are expected there (they're in the commit as well, as this is an external header, thus we don't enforce the 'space-only' policy there). The *broken* patch in this case seems to be `42-0002-network-add-CAN-Termination-tristate-option.patch` => `error: src/network/networkd-network-gperf.gperf: patch does not apply`

If you have the SRPM at hand, that would be much appreciated.

**Comment by TomasTomecek** [comment]
but I can't see the tabs in the commit, only in the generated patch :x I'll send the SRPM to you

**Comment by TomasTomecek** [comment]
Oki, you're correct, I can see the tabs in the code now - `less` was turning them into spaces.

**Comment by mrc0mmand** [comment]
@TomasTomecek I think I see the problem and it's not nice...

The culprit here are, as expected, merge commits, and apparently `git format-patch` can't generate patches which can be then applied in a fast-forward way:

```
$ cd ~/work/ci-incubator/systemd
$ mkdir _test && cd _test
$ git format-patch v245..HEAD
$ ls *.patch | wc -l
143
$ git reset --hard v245
HEAD is now at ea500ac513 Merge pull request #15034 from keszybz/hwdb-update
$ git am *.patch
...
Applying: udev: support to update flow control parameter
Applying: linux: add can/netlink.h
.git/rebase-apply/patch:43: tab in indent.
	__u32 bitrate;		/* Bit-rate in bits/second */
.git/rebase-apply/patch:44: tab in indent.
	__u32 sample_point;	/* Sample point in one-tenth of a percent */
.git/rebase-apply/patch:45: tab in indent.
	__u32 tq;		/* Time quanta (TQ) in nanoseconds */
.git/rebase-apply/patch:46: tab in indent.
	__u32 prop_seg;		/* Propagation segment in TQs */
.git/rebase-apply/patch:47: tab in indent.
	__u32 phase_seg1;	/* Phase buffer segment 1 in TQs */
warning: squelched 47 whitespace errors
warning: 52 lines add whitespace errors.
Applying: network: add CAN Termination tristate option
error: patch failed: src/network/networkd-network-gperf.gperf:251
error: src/network/networkd-network-gperf.gperf: patch does not apply
Patch failed at 0044 network: add CAN Termination tristate option
hint: Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
```

However, if I tell `git am` to fall back to a 3-way merge when necessary (`--3way`), everything works as expected

```
$ git am --abort
$ git am --3way *.patch
...
Applying: network: add CAN Termination tristate option
Using index info to reconstruct a base tree...
M	man/systemd.network.xml
M	src/libsystemd/sd-netlink/netlink-types.c
M	src/network/networkd-network-gperf.gperf
M	src/network/networkd-network.c
M	src/network/networkd-network.h
M	test/fuzz/fuzz-network-parser/directives.network
Falling back to patching base and 3-way merge...
Auto-merging test/fuzz/fuzz-network-parser/directives.network
Auto-merging src/network/networkd-network.h
Auto-merging src/network/networkd-network.c
Auto-merging src/network/networkd-network-gperf.gperf
Auto-merging src/libsystemd/sd-netlink/netlink-types.c
Auto-merging man/systemd.network.xml
Applying: docs: fix misplaced close-paren
...
Applying: sd-bus: sd_bus_set/get_method_call_timeout docs + cleanups.
Using index info to reconstruct a base tree...
M	man/rules/meson.build
M	man/sd-bus.xml
M	man/sd_bus_set_description.xml
Falling back to patching base and 3-way merge...
Auto-merging man/sd_bus_set_description.xml
Auto-merging man/sd-bus.xml
Auto-merging man/rules/meson.build
Applying: selinux: delay mac_selinux_enforcing call after SELinux was determined to be enabled
...
Applying: packit: initial config
```

**Comment by TomasTomecek** [comment]
so could you make the history linear?

**Comment by mrc0mmand** [comment]
Ah, darn, so this won't work as well...

With this *beautiful* patch both `-S git` and `-S git_am` use a 3-way merge when necessary:
```diff
diff --git a/tools/packaging/rpm/systemd.spec b/tools/packaging/rpm/systemd.spec
index 8765572e41..37141da731 100644
--- a/tools/packaging/rpm/systemd.spec
+++ b/tools/packaging/rpm/systemd.spec
@@ -292,6 +292,12 @@ License:       LGPLv2+
 They can be useful to test systemd internals.
 
 %prep
+%define __scm_apply_git_am(qp:m:)\
+%{__git} am --3way %{-q} %{-p:-p%{-p*}}
+%define __scm_apply_git(qp:m:)\
+%{__git} apply --3way --index %{-p:-p%{-p*}} -\
+%{__git} commit %{-q} -m %{-m*} --author "%{__scm_author}"
+
 %autosetup -n %{?commit:%{name}%{?stable:-stable}-%{commit}}%{!?commit:%{name}%{?stable:-stable}-%{github_version}} -p1 -Sgit
 
 %build
```
(it basically overrides the internal macros defined in `/usr/lib/rpm/macros`).

BUT it won't work, since we work on a tarball, thus missing the necessary references...

@TomasTomecek frankly, I don't know how to continue with this any further from my side.

**Comment by TomasTomecek** [comment]
honestly, a solution would be to generate a tarball from HEAD and basically don't do any downstream patches

**Comment by mrc0mmand** [comment]
> honestly, a solution would be to generate a tarball from HEAD and basically don't do any downstream patches

I guess that would be definitely cleaner and easier than a solution i proposed in https://github.com/packit-service/packit/pull/766#issuecomment-602030852.

**Comment by mrc0mmand** [comment]
So, without specifying `upstream_ref` in `.packit.yml` the build seems to work (thanks, @msekletar!). The only issue now is failing `test-mountpoint-util` because the kernel on the build machines is missing a certain fix (see https://bugzilla.redhat.com/show_bug.cgi?id=1803070). I'll go ahead and temporarily disable it.

**Comment by thrix** [comment]
testing farm passed \o/

**Comment by mrc0mmand** [comment]
Oh yes, will start tomorrow with writing some *useful* tests :tada:

**Comment by mrc0mmand** [comment]
I'm going to merge this one, since the integration with TFT is working as expected, and open another PR just to be able to trigger the tests.

**Comment by msekletar** [comment]
@mrc0mmand Thank you for getting the initial integration work done.

**Pull request merged**
